 /*
const es = {
  menu: {
    inicio: 'Inicio',
    tours: 'Tours',
    sedes: 'Sedes',
    sobreNosotros: 'Sobre Nosotros',
    contacto: 'Contacto',
    preguntasFrecuentes: 'Preguntas Frecuentes'
  },
  autenticacion: {
    ingresar: 'Ingresar',
    registrarse: 'Registrarse',
    cerrarSesion: 'Cerrar Sesión'
  },
  idioma: {
    cambiar: 'Cambiar idioma'
  },
  hero: {
    slide1: {
      titulo: 'Descubre la Belleza Marina de Pisco',
      subtitulo: 'Experiencias únicas en las costas del Perú'
    },
    slide2: {
      titulo: 'Vive Aventuras Inolvidables',
      subtitulo: 'Tours exclusivos para toda la familia'
    },
    slide3: {
      titulo: 'Naturaleza y Biodiversidad',
      subtitulo: 'Explora la reserva natural más impresionante de Perú'
    },
    botonExplorar: 'Explorar Tours',
    botonContacto: 'Contáctanos'
  },
  inicio: {
    toursDestacados: 'Tours Destacados',
    toursDestacadosDescripcion: 'Descubre nuestros tours más populares y disfruta de experiencias inolvidables.',
    verTodosTours: 'Ver todos los tours',
    porQueElegirnos: '¿Por qué elegirnos?',
    porQueElegirnosDescripcion: 'Ofrecemos experiencias únicas con el mejor servicio y seguridad.',
    seguridad: 'Seguridad Garantizada',
    seguridadDescripcion: 'Tu seguridad es nuestra prioridad. Nuestras embarcaciones cumplen con todos los estándares de seguridad.',
    calidad: 'Calidad Superior',
    calidadDescripcion: 'Servicio de primera clase con guías expertos y embarcaciones modernas y cómodas.',
    experiencia: 'Experiencias Únicas',
    experienciaDescripcion: 'Vivencias inolvidables diseñadas para superar tus expectativas.',
    testimonios: 'Lo que dicen nuestros clientes',
    testimoniosDescripcion: 'Conoce las experiencias de quienes ya han disfrutado de nuestros tours.',
    socios: 'Nuestros Socios',
    sociosDescripcion: 'Trabajamos con las mejores empresas para brindarte un servicio excepcional.'
  },
  footer: {
    descripcion: 'Somos líderes en tours marítimos en Pisco, Perú, ofreciendo experiencias únicas para explorar la belleza natural de nuestras costas.',
    enlacesRapidos: 'Enlaces Rápidos',
    contacto: 'Contacto',
    horario: 'Horario',
    boletin: 'Boletín Informativo',
    boletinDescripcion: 'Suscríbete a nuestro boletín para recibir ofertas y novedades.',
    correoPlaceholder: 'Tu correo electrónico',
    suscribirse: 'Suscribirse',
    derechosReservados: 'Todos los derechos reservados.',
    terminos: 'Términos y Condiciones',
    privacidad: 'Política de Privacidad',
    cookies: 'Política de Cookies'
  },
  boletin: {
    titulo: 'Mantente Informado',
    descripcion: 'Suscríbete a nuestro boletín para recibir ofertas exclusivas, consejos de viaje y las últimas novedades.',
    beneficio1Titulo: 'Ofertas Exclusivas',
    beneficio1Descripcion: 'Accede a promociones y descuentos especiales solo para suscriptores.',
    beneficio2Titulo: 'Novedades al Instante',
    beneficio2Descripcion: 'Sé el primero en conocer nuevos tours y actividades.',
    formTitulo: 'Únete a nuestra comunidad',
    correo: 'Correo Electrónico',
    correoPlaceholder: 'ejemplo@correo.com',
    nombre: 'Nombre',
    nombrePlaceholder: 'Tu nombre',
    recibirOfertas: 'Quiero recibir ofertas especiales y novedades',
    suscribirse: 'Suscribirme Ahora',
    privacidad: 'Al suscribirte, aceptas nuestra política de privacidad y términos de uso.',
    errorVacio: 'Por favor ingresa tu correo electrónico.',
    errorInvalido: 'Por favor ingresa un correo electrónico válido.',
    errorServidor: 'Hubo un error al procesar tu solicitud. Inténtalo de nuevo.',
    exitoTitulo: '¡Gracias por suscribirte!',
    exitoDescripcion: 'Pronto recibirás nuestras novedades y ofertas exclusivas en tu correo.',
    suscribirOtro: 'Suscribir otro correo'
  },
  404: {
    titulo: '¡Página no encontrada!',
    descripcion: 'Lo sentimos, la página que estás buscando no existe o ha sido movida.',
    volverInicio: 'Volver al inicio',
    contactarSoporte: 'Contactar soporte',
    sugerencias: 'Quizás te interese:'
  },
  validacion: {
    requerido: 'Este campo es requerido',
    correoInvalido: 'Por favor ingresa un correo electrónico válido',
    dniInvalido: 'El DNI debe tener 8 dígitos',
    contrasenaCorta: 'La contraseña debe tener al menos 6 caracteres',
    contrasenaNoCoincide: 'Las contraseñas no coinciden'
  },
  registro: {
    titulo: 'Crea tu cuenta',
    descripcion: 'Únete a nosotros y disfruta de beneficios exclusivos.',
    nombres: 'Nombres',
    apellidos: 'Apellidos',
    tipoDocumento: 'Tipo de Documento',
    numeroDocumento: 'Número de Documento',
    correo: 'Correo Electrónico',
    telefono: 'Teléfono',
    contrasena: 'Contraseña',
    confirmarContrasena: 'Confirmar Contraseña',
    aceptoTerminos: 'Acepto los',
    terminos: 'términos y condiciones',
    crearCuenta: 'Crear Cuenta',
    yaTienesCuenta: '¿Ya tienes una cuenta?',
    iniciarSesion: 'Iniciar Sesión',
    exitoso: '¡Cuenta creada exitosamente!',
    error: 'Hubo un error al crear la cuenta. Inténtalo de nuevo.',
    beneficio1Titulo: 'Reservas más rápidas',
    beneficio1Descripcion: 'Guarda tus datos para reservar con solo un clic.',
    beneficio2Titulo: 'Historial de tours',
    beneficio2Descripcion: 'Accede a tu historial de tours y reservas.',
    beneficio3Titulo: 'Promociones exclusivas',
    beneficio3Descripcion: 'Recibe ofertas especiales solo para usuarios registrados.'
  },
  recuperacion: {
    titulo: 'Recupera tu contraseña',
    descripcion: 'Ingresa tu correo electrónico y te enviaremos instrucciones para recuperar tu contraseña.',
    correo: 'Correo Electrónico',
    enviarInstrucciones: 'Enviar Instrucciones',
    recordaste: '¿Recordaste tu contraseña?',
    volverLogin: 'Volver a iniciar sesión',
    correoRequerido: 'Por favor ingresa tu correo electrónico.',
    correoInvalido: 'Por favor ingresa un correo electrónico válido.',
    errorEnvio: 'Hubo un error al enviar las instrucciones. Inténtalo de nuevo.',
    correoEnviado: 'Instrucciones enviadas',
    instrucciones: 'Hemos enviado instrucciones para recuperar tu contraseña a tu correo electrónico. Por favor revisa tu bandeja de entrada.',
    volverInicio: 'Volver al inicio',
    intentarOtroCorreo: 'Intentar con otro correo'
  },
  // Añade esta sección a tu objeto es
contacto: {
  titulo: 'Contáctanos',
  subtitulo: 'Estamos aquí para responder cualquier pregunta que tengas',
  infoTitulo: 'Información de Contacto',
  infoDescripcion: 'Comunícate con nosotros a través de cualquiera de estos medios. Estaremos encantados de atenderte.',
  telefono: 'Teléfono',
  email: 'Correo Electrónico',
  direccion: 'Dirección',
  horario: 'Horario de Atención',
  redesSociales: 'Síguenos en redes sociales',
  formTitulo: 'Envíanos un mensaje',
  nombre: 'Nombre Completo',
  asunto: 'Asunto',
  mensaje: 'Mensaje',
  sede: 'Sede',
  sedePisco: 'Pisco',
  sedeParacas: 'Paracas',
  sedeSanAndres: 'San Andrés',
  enviar: 'Enviar Mensaje',
  enviando: 'Enviando...',
  mensajeExito: '¡Mensaje enviado correctamente! Nos pondremos en contacto contigo pronto.',
  faqTitulo: 'Preguntas Frecuentes',
  faqDescripcion: 'Respuestas a las preguntas más comunes sobre nuestros servicios.',
  faq1Pregunta: '¿Cuáles son los horarios de los tours?',
  faq1Respuesta: 'Nuestros tours operan todos los días desde las 8:00 AM hasta las 5:00 PM.',
  faq2Pregunta: '¿Cómo puedo hacer una reserva?',
  faq2Respuesta: 'Puedes hacer una reserva directamente en nuestro sitio web, por teléfono o visitando nuestras oficinas.',
  faq3Pregunta: '¿Qué pasa si quiero cancelar mi reserva?',
  faq3Respuesta: 'Las cancelaciones realizadas con más de 48 horas de anticipación reciben un reembolso completo.',
  faq4Pregunta: '¿Los tours incluyen transporte desde el hotel?',
  faq4Respuesta: 'Sí, todos nuestros tours incluyen recogida y retorno a hoteles en el centro de la ciudad.',
  faq5Pregunta: '¿Qué debo llevar para los tours marítimos?',
  faq5Respuesta: 'Recomendamos traer protector solar, gafas de sol, una gorra o sombrero, y ropa ligera.',
  masPreguntas: '¿Tienes más preguntas?',
  verMasPreguntas: 'Ver todas las preguntas frecuentes'
},
 
  
  conservacion: {
    titulo: 'Conservación y Responsabilidad Social',
    subtitulo: 'En Ocean Tours, creemos que el turismo responsable debe contribuir a la preservación de los ecosistemas marinos y el bienestar de las comunidades locales.',
    
    proteccionTitulo: 'Protección de Especies Marinas',
    proteccionDescripcion: 'Nuestros tours están diseñados para observar la vida marina sin perturbar su hábitat natural',
    
    iniciativasTitulo: 'Nuestras Iniciativas de Conservación',
    iniciativa1Titulo: 'Programa de Limpieza de Playas',
    iniciativa1Descripcion: 'Organizamos limpiezas mensuales de playas con la participación de voluntarios y nuestro personal, recolectando residuos plásticos y otros desechos.',
    iniciativa2Titulo: 'Educación Ambiental',
    iniciativa2Descripcion: 'Durante nuestros tours, educamos a los visitantes sobre la importancia de la conservación marina y cómo pueden contribuir a proteger estos ecosistemas frágiles.',
    iniciativa3Titulo: 'Apoyo a Investigaciones',
    iniciativa3Descripcion: 'Colaboramos con instituciones locales en estudios de monitoreo de poblaciones de aves marinas y mamíferos marinos como lobos marinos y delfines.',
    saberMas: 'Saber más sobre nuestras iniciativas',
    
    impactoTitulo: 'Impacto Social',
    impactoSubtitulo: 'Trabajamos estrechamente con las comunidades locales para asegurar que el turismo beneficie directamente a los habitantes de Paracas.',
    
    empleoTitulo: 'Empleo Local',
    empleoDescripcion: 'El 90% de nuestro personal son residentes locales. Brindamos capacitación constante y oportunidades de desarrollo profesional.',
    
    educacionTitulo: 'Educación Comunitaria',
    educacionDescripcion: 'Ofrecemos programas educativos gratuitos para niños locales sobre conservación marina y turismo sostenible.',
    
    artesanosTitulo: 'Apoyo a Artesanos',
    artesanosDescripcion: 'Promovemos el trabajo de artesanos locales, vendiendo sus productos en nuestras tiendas y brindando espacios para mostrar su arte.',
    
    especiesTitulo: 'Especies que Protegemos',
    pingüinos: 'Pingüinos de Humboldt',
    pingüinosDesc: 'Especie vulnerable que habita en la Reserva Nacional de Paracas',
    lobos: 'Lobos Marinos',
    lobosDesc: 'Colonias importantes en las Islas Ballestas que monitoreamos constantemente',
    delfines: 'Delfines y Ballenas',
    delfinesDesc: 'Respetamos estrictas normas de observación para no perturbar su comportamiento natural',
    
    uneteTitulo: 'Únete a Nuestros Esfuerzos de Conservación',
    uneteDescripcion: 'Al elegir Ocean Tours, estás contribuyendo directamente a nuestras iniciativas de conservación. También puedes participar activamente en nuestros programas de voluntariado.',
    contactar: 'Contactar para Voluntariado',
    explorarTours: 'Explorar Tours Sostenibles',
    
    certificacionesTitulo: 'Nuestras Certificaciones y Alianzas'
  },
  
 reserva: {
    estados: {
      confirmada: 'Confirmada',
      reservado: 'Reservada',
      pendiente: 'Pendiente',
      cancelada: 'Cancelada',
      procesado: 'Procesada',
      anulado: 'Anulada'
    },
    gestionReservas: 'Gestiona tus reservas y planifica tu próxima aventura',
    sinReservas: 'No hay reservas disponibles',
    sinReservasEstado: 'No hay reservas en estado {estado}',
    fechaNoDisponible: 'Fecha no disponible',
    fechaInvalida: 'Fecha inválida',
    hoy: 'Hoy',
    manana: 'Mañana',
    ayer: 'Ayer',
    enDias: 'En {dias} días',
    haceDias: 'Hace {dias} días',
    tourNoEspecificado: 'Tour no especificado',
    horarioNoEspecificado: 'Horario no especificado',
    noSesion: 'No has iniciado sesión',
    iniciarSesionParaVerReservas: 'Inicia sesión para ver tus reservas',
    explorarTours: 'Explora nuestros tours y reserva tu próxima aventura',
    todos: 'Todos',
    verTours: 'Ver Tours',
    fecha: 'Fecha',
    pasajeros: 'Pasajeros',
    total: 'Total',
    estado: 'Estado',
    acciones: 'Acciones',
    verDetalles: 'Ver Detalles',
    filtrarPorEstado: 'Filtrar por estado',
    reservadoEl: 'Reservado el',
    estadisticasReservas: 'Estadísticas de Reservas'
  },

};

export default es;*/


const es = {
  menu: {
    inicio: 'Inicio',
    tours: 'Tours',
    sedes: 'Sedes',
    sobreNosotros: 'Sobre Nosotros',
    contacto: 'Contacto',
    preguntasFrecuentes: 'Preguntas Frecuentes'
  },
  autenticacion: {
    ingresar: 'Ingresar',
    registrarse: 'Registrarse',
    cerrarSesion: 'Cerrar Sesión'
  },
  idioma: {
    cambiar: 'Cambiar idioma'
  },
  hero: {
    slide1: {
      titulo: 'Descubre la Belleza Marina de Pisco',
      subtitulo: 'Experiencias únicas en las costas del Perú'
    },
    slide2: {
      titulo: 'Vive Aventuras Inolvidables',
      subtitulo: 'Tours exclusivos para toda la familia'
    },
    slide3: {
      titulo: 'Naturaleza y Biodiversidad',
      subtitulo: 'Explora la reserva natural más impresionante de Perú'
    },
    botonExplorar: 'Explorar Tours',
    botonContacto: 'Contáctanos'
  },
  inicio: {
    toursDestacados: 'Tours Destacados',
    toursDestacadosDescripcion: 'Descubre nuestros tours más populares y disfruta de experiencias inolvidables.',
    verTodosTours: 'Ver todos los tours',
    porQueElegirnos: '¿Por qué elegirnos?',
    porQueElegirnosDescripcion: 'Ofrecemos experiencias únicas con el mejor servicio y seguridad.',
    seguridad: 'Seguridad Garantizada',
    seguridadDescripcion: 'Tu seguridad es nuestra prioridad. Nuestras embarcaciones cumplen con todos los estándares de seguridad.',
    calidad: 'Calidad Superior',
    calidadDescripcion: 'Servicio de primera clase con guías expertos y embarcaciones modernas y cómodas.',
    experiencia: 'Experiencias Únicas',
    experienciaDescripcion: 'Vivencias inolvidables diseñadas para superar tus expectativas.',
    testimonios: 'Lo que dicen nuestros clientes',
    testimoniosDescripcion: 'Conoce las experiencias de quienes ya han disfrutado de nuestros tours.',
    socios: 'Nuestros Socios',
    sociosDescripcion: 'Trabajamos con las mejores empresas para brindarte un servicio excepcional.'
  },
  footer: {
    descripcion: 'Somos líderes en tours marítimos en Pisco, Perú, ofreciendo experiencias únicas para explorar la belleza natural de nuestras costas.',
    enlacesRapidos: 'Enlaces Rápidos',
    contacto: 'Contacto',
    horario: 'Horario',
    boletin: 'Boletín Informativo',
    boletinDescripcion: 'Suscríbete a nuestro boletín para recibir ofertas y novedades.',
    correoPlaceholder: 'Tu correo electrónico',
    suscribirse: 'Suscribirse',
    derechosReservados: 'Todos los derechos reservados.',
    terminos: 'Términos y Condiciones',
    privacidad: 'Política de Privacidad',
    cookies: 'Política de Cookies'
  },
  boletin: {
    titulo: 'Mantente Informado',
    descripcion: 'Suscríbete a nuestro boletín para recibir ofertas exclusivas, consejos de viaje y las últimas novedades.',
    beneficio1Titulo: 'Ofertas Exclusivas',
    beneficio1Descripcion: 'Accede a promociones y descuentos especiales solo para suscriptores.',
    beneficio2Titulo: 'Novedades al Instante',
    beneficio2Descripcion: 'Sé el primero en conocer nuevos tours y actividades.',
    formTitulo: 'Únete a nuestra comunidad',
    correo: 'Correo Electrónico',
    correoPlaceholder: 'ejemplo@correo.com',
    nombre: 'Nombre',
    nombrePlaceholder: 'Tu nombre',
    recibirOfertas: 'Quiero recibir ofertas especiales y novedades',
    suscribirse: 'Suscribirme Ahora',
    privacidad: 'Al suscribirte, aceptas nuestra política de privacidad y términos de uso.',
    errorVacio: 'Por favor ingresa tu correo electrónico.',
    errorInvalido: 'Por favor ingresa un correo electrónico válido.',
    errorServidor: 'Hubo un error al procesar tu solicitud. Inténtalo de nuevo.',
    exitoTitulo: '¡Gracias por suscribirte!',
    exitoDescripcion: 'Pronto recibirás nuestras novedades y ofertas exclusivas en tu correo.',
    suscribirOtro: 'Suscribir otro correo'
  },
  404: {
    titulo: '¡Página no encontrada!',
    descripcion: 'Lo sentimos, la página que estás buscando no existe o ha sido movida.',
    volverInicio: 'Volver al inicio',
    contactarSoporte: 'Contactar soporte',
    sugerencias: 'Quizás te interese:'
  },
  validacion: {
    requerido: 'Este campo es requerido',
    correoInvalido: 'Por favor ingresa un correo electrónico válido',
    dniInvalido: 'El DNI debe tener 8 dígitos',
    contrasenaCorta: 'La contraseña debe tener al menos 6 caracteres',
    contrasenaNoCoincide: 'Las contraseñas no coinciden'
  },
  registro: {
    titulo: 'Crea tu cuenta',
    descripcion: 'Únete a nosotros y disfruta de beneficios exclusivos.',
    nombres: 'Nombres',
    apellidos: 'Apellidos',
    tipoDocumento: 'Tipo de Documento',
    numeroDocumento: 'Número de Documento',
    correo: 'Correo Electrónico',
    telefono: 'Teléfono',
    contrasena: 'Contraseña',
    confirmarContrasena: 'Confirmar Contraseña',
    aceptoTerminos: 'Acepto los',
    terminos: 'términos y condiciones',
    crearCuenta: 'Crear Cuenta',
    yaTienesCuenta: '¿Ya tienes una cuenta?',
    iniciarSesion: 'Iniciar Sesión',
    exitoso: '¡Cuenta creada exitosamente!',
    error: 'Hubo un error al crear la cuenta. Inténtalo de nuevo.',
    beneficio1Titulo: 'Reservas más rápidas',
    beneficio1Descripcion: 'Guarda tus datos para reservar con solo un clic.',
    beneficio2Titulo: 'Historial de tours',
    beneficio2Descripcion: 'Accede a tu historial de tours y reservas.',
    beneficio3Titulo: 'Promociones exclusivas',
    beneficio3Descripcion: 'Recibe ofertas especiales solo para usuarios registrados.'
  },
  recuperacion: {
    titulo: 'Recupera tu contraseña',
    descripcion: 'Ingresa tu correo electrónico y te enviaremos instrucciones para recuperar tu contraseña.',
    correo: 'Correo Electrónico',
    enviarInstrucciones: 'Enviar Instrucciones',
    recordaste: '¿Recordaste tu contraseña?',
    volverLogin: 'Volver a iniciar sesión',
    correoRequerido: 'Por favor ingresa tu correo electrónico.',
    correoInvalido: 'Por favor ingresa un correo electrónico válido.',
    errorEnvio: 'Hubo un error al enviar las instrucciones. Inténtalo de nuevo.',
    correoEnviado: 'Instrucciones enviadas',
    instrucciones: 'Hemos enviado instrucciones para recuperar tu contraseña a tu correo electrónico. Por favor revisa tu bandeja de entrada.',
    volverInicio: 'Volver al inicio',
    intentarOtroCorreo: 'Intentar con otro correo'
  },
  contacto: {
    titulo: 'Contáctanos',
    subtitulo: 'Estamos aquí para responder cualquier pregunta que tengas',
    infoTitulo: 'Información de Contacto',
    infoDescripcion: 'Comunícate con nosotros a través de cualquiera de estos medios. Estaremos encantados de atenderte.',
    telefono: 'Teléfono',
    email: 'Correo Electrónico',
    direccion: 'Dirección',
    horario: 'Horario de Atención',
    redesSociales: 'Síguenos en redes sociales',
    formTitulo: 'Envíanos un mensaje',
    nombre: 'Nombre Completo',
    asunto: 'Asunto',
    mensaje: 'Mensaje',
    sede: 'Sede',
    sedePisco: 'Pisco',
    sedeParacas: 'Paracas',
    sedeSanAndres: 'San Andrés',
    enviar: 'Enviar Mensaje',
    enviando: 'Enviando...',
    mensajeExito: '¡Mensaje enviado correctamente! Nos pondremos en contacto contigo pronto.',
    faqTitulo: 'Preguntas Frecuentes',
    faqDescripcion: 'Respuestas a las preguntas más comunes sobre nuestros servicios.',
    faq1Pregunta: '¿Cuáles son los horarios de los tours?',
    faq1Respuesta: 'Nuestros tours operan todos los días desde las 8:00 AM hasta las 5:00 PM.',
    faq2Pregunta: '¿Cómo puedo hacer una reserva?',
    faq2Respuesta: 'Puedes hacer una reserva directamente en nuestro sitio web, por teléfono o visitando nuestras oficinas.',
    faq3Pregunta: '¿Qué pasa si quiero cancelar mi reserva?',
    faq3Respuesta: 'Las cancelaciones realizadas con más de 48 horas de anticipación reciben un reembolso completo.',
    faq4Pregunta: '¿Los tours incluyen transporte desde el hotel?',
    faq4Respuesta: 'Sí, todos nuestros tours incluyen recogida y retorno a hoteles en el centro de la ciudad.',
    faq5Pregunta: '¿Qué debo llevar para los tours marítimos?',
    faq5Respuesta: 'Recomendamos traer protector solar, gafas de sol, una gorra o sombrero, y ropa ligera.',
    masPreguntas: '¿Tienes más preguntas?',
    verMasPreguntas: 'Ver todas las preguntas frecuentes'
  },
  conservacion: {
    titulo: 'Conservación y Responsabilidad Social',
    subtitulo: 'En Ocean Tours, creemos que el turismo responsable debe contribuir a la preservación de los ecosistemas marinos y el bienestar de las comunidades locales.',
    proteccionTitulo: 'Protección de Especies Marinas',
    proteccionDescripcion: 'Nuestros tours están diseñados para observar la vida marina sin perturbar su hábitat natural',
    iniciativasTitulo: 'Nuestras Iniciativas de Conservación',
    iniciativa1Titulo: 'Programa de Limpieza de Playas',
    iniciativa1Descripcion: 'Organizamos limpiezas mensuales de playas con la participación de voluntarios y nuestro personal, recolectando residuos plásticos y otros desechos.',
    iniciativa2Titulo: 'Educación Ambiental',
    iniciativa2Descripcion: 'Durante nuestros tours, educamos a los visitantes sobre la importancia de la conservación marina y cómo pueden contribuir a proteger estos ecosistemas frágiles.',
    iniciativa3Titulo: 'Apoyo a Investigaciones',
    iniciativa3Descripcion: 'Colaboramos con instituciones locales en estudios de monitoreo de poblaciones de aves marinas y mamíferos marinos como lobos marinos y delfines.',
    saberMas: 'Saber más sobre nuestras iniciativas',
    impactoTitulo: 'Impacto Social',
    impactoSubtitulo: 'Trabajamos estrechamente con las comunidades locales para asegurar que el turismo beneficie directamente a los habitantes de Paracas.',
    empleoTitulo: 'Empleo Local',
    empleoDescripcion: 'El 90% de nuestro personal son residentes locales. Brindamos capacitación constante y oportunidades de desarrollo profesional.',
    educacionTitulo: 'Educación Comunitaria',
    educacionDescripcion: 'Ofrecemos programas educativos gratuitos para niños locales sobre conservación marina y turismo sostenible.',
    artesanosTitulo: 'Apoyo a Artesanos',
    artesanosDescripcion: 'Promovemos el trabajo de artesanos locales, vendiendo sus productos en nuestras tiendas y brindando espacios para mostrar su arte.',
    especiesTitulo: 'Especies que Protegemos',
    pingüinos: 'Pingüinos de Humboldt',
    pingüinosDesc: 'Especie vulnerable que habita en la Reserva Nacional de Paracas',
    lobos: 'Lobos Marinos',
    lobosDesc: 'Colonias importantes en las Islas Ballestas que monitoreamos constantemente',
    delfines: 'Delfines y Ballenas',
    delfinesDesc: 'Respetamos estrictas normas de observación para no perturbar su comportamiento natural',
    uneteTitulo: 'Únete a Nuestros Esfuerzos de Conservación',
    uneteDescripcion: 'Al elegir Ocean Tours, estás contribuyendo directamente a nuestras iniciativas de conservación. También puedes participar activamente en nuestros programas de voluntariado.',
    contactar: 'Contactar para Voluntariado',
    explorarTours: 'Explorar Tours Sostenibles',
    certificacionesTitulo: 'Nuestras Certificaciones y Alianzas'
  },
  reserva: {
    estados: {
      confirmada: 'Confirmada',
      reservado: 'Reservada',
      pendiente: 'Pendiente',
      cancelada: 'Cancelada',
      procesado: 'Procesada',
      anulado: 'Anulada'
    },
    gestionReservas: 'Gestiona tus reservas y planifica tu próxima aventura',
    sinReservas: 'No hay reservas disponibles',
    sinReservasEstado: 'No hay reservas en estado {estado}',
    fechaNoDisponible: 'Fecha no disponible',
    fechaInvalida: 'Fecha inválida',
    hoy: 'Hoy',
    manana: 'Mañana',
    ayer: 'Ayer',
    enDias: 'En {dias} días',
    haceDias: 'Hace {dias} días',
    tourNoEspecificado: 'Tour no especificado',
    horarioNoEspecificado: 'Horario no especificado',
    noSesion: 'No has iniciado sesión',
    iniciarSesionParaVerReservas: 'Inicia sesión para ver tus reservas',
    explorarTours: 'Explora nuestros tours y reserva tu próxima aventura',
    todos: 'Todos',
    verTours: 'Ver Tours',
    fecha: 'Fecha',
    pasajeros: 'Pasajeros',
    total: 'Total',
    estado: 'Estado',
    acciones: 'Acciones',
    verDetalles: 'Ver Detalles',
    filtrarPorEstado: 'Filtrar por estado',
    reservadoEl: 'Reservado el',
    estadisticasReservas: 'Estadísticas de Reservas'
  },
  // 🔧 NUEVAS CLAVES PARA FORMULARIO DE RESERVACIÓN
  general: {
    cargando: 'Cargando...',
    importante: 'Importante',
    email: 'Email',
    horario: 'Horario',
    atencion: 'Atención',
    horarioDetalles: 'Lunes a Domingo 8am-8pm',
    continuar: 'Continuar',
    volver: 'Volver',
    procesando: 'Procesando...',
    cerrar: 'Cerrar'
  },
  tour: {
    reservarAhora: 'Reservar Ahora',
    porPersona: 'por persona',
    fechaYHora: 'Fecha y Hora',
    pasajeros: 'Pasajeros',
    seleccionaFechaHorario: 'Selecciona fecha y horario',
    fecha: 'Fecha',
    seleccionarFecha: 'Seleccionar fecha',
    horario: 'Horario',
    seleccionarHorario: 'Seleccionar horario',
    seleccionePrimeroFecha: 'Seleccione primero una fecha',
    cargandoFechas: 'Cargando fechas disponibles...',
    hayFechasDisponibles: 'Fechas disponibles',
    yMas: 'y {count} más',
    sinFechasDisponibles: 'No hay fechas disponibles',
    sinHorariosDisponiblesParaFecha: 'No hay horarios disponibles para esta fecha',
    sinCupo: 'Sin cupo',
    disponible: 'Disponible',
    seleccionActual: 'Selección actual',
    seleccionaPasajes: 'Selecciona pasajeros',
    paquetesPromocion: 'Paquetes de Promoción',
    pasajesIndividuales: 'Pasajes Individuales',
    noHayTiposPasajeDisponibles: 'No hay tipos de pasaje disponibles',
    combinar: 'También puedes combinar',
    cantidad: 'Cantidad',
    reducirCantidad: 'Reducir cantidad',
    aumentarCantidad: 'Aumentar cantidad',
    subtotal: 'Subtotal',
    totalPasajeros: 'Total de pasajeros',
    totalPagar: 'Total a pagar',
    continuarPago: 'Continuar al pago',
    pagoSeguro: 'Pago Seguro',
    metodosPago: 'Métodos de pago aceptados',
    pagoCifrado: 'Transacciones cifradas y seguras',
    seleccionePasajeOPaquete: 'Selecciona al menos un pasaje o paquete',
    noCupoDisponible: 'No hay cupo disponible. Disponible',
    solicitado: 'solicitado',
    reserva24Horas: 'Las reservas deben realizarse con mínimo 24 horas de anticipación.',
    pagoCompleto: 'Se requiere pago completo al momento de la reserva.',
    notaPagoCompleto: 'El pago debe realizarse de forma completa al momento de confirmar la reserva.',
    nota24Horas: 'Las reservas deben realizarse con un mínimo de 24 horas de anticipación.',
    notaPrecios: 'Los precios mostrados incluyen todos los impuestos aplicables.',
    notaConfirmacion: 'Recibirás una confirmación por email una vez completado el pago.',
    cargandoReserva: 'Cargando sistema de reservas'
  },
  // 🔧 NUEVAS CLAVES PARA PROCESO DE PAGO
  pago: {
    titulo: 'Proceso de Pago',
    subtitulo: 'Completa tu reserva realizando el pago'
  }
};

export default es;