version: '3.8'

services:
 PaginaWebb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PaginaWebb-container
    network_mode: host
    volumes:
      - ./certs:/etc/nginx/certs:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped