- name: Crear archivo de SSH key
  run: |
    mkdir -p ~/.ssh/
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    
- name: Transferir archivos al servidor
  run: |
    rsync -avz --exclude 'node_modules' --exclude '.git' \
      ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/sistema-tours/
    
- name: Ejecutar despliegue en servidor
  run: |
    ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /home/${{ secrets.SERVER_USER }}/sistema-tours && \
      docker-compose down && \
      docker-compose up -d --build"