name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configurar entorno
      run: |
        echo "Configurando el entorno..."
        
    - name: Ejecutar pruebas
      run: |
        echo "Ejecutando pruebas..."
        
    - name: Construir aplicaci贸n
      run: |
        echo "Construyendo aplicaci贸n..."
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Desplegar a producci贸n
      run: |
        echo "Desplegando a producci贸n..."